services:
  authserver:
    container_name: authserver
    image: ghcr.io/navikt/mock-oauth2-server:2.1.1
    environment:
      TZ: Europe/Oslo
      SERVER_PORT: 6969
      JSON_CONFIG: >
        {
          "interactiveLogin": true,
          "tokenCallbacks": [
            {
              "issuerId": "azure",
              "tokenExpiry": 3600,
              "requestMappings": [
                {
                  "requestParam": "requested_token_use",
                  "match":"on_behalf_of",
                  "claims": {
                    "aud": ["lydia-api"],
                    "NAVident": "Z123456",
                    "preferred_username": "test.testesen@nav.no",
                    "name": "Test Testesen",
                    "groups": ["ensuperbrukerGroupId"]
                  }
                },                
                {
                  "match":"*",
                  "requestParam": "grant_type",
                  "claims": {
                    "aud": ["fia-frontend"],
                    "NAVident": "Z123456",
                    "preferred_username": "test.testesen@nav.no",
                    "name": "Test Testesen",
                    "groups": ["ensuperbrukerGroupId"]
                  }
                }
              ]
            }
          ]
        }
    ports:
      - 6969:6969
    restart: unless-stopped

  wonderwall:
    image: ghcr.io/nais/wonderwall:latest
    container_name: wonderwall
    depends_on:
      - authserver
    ports:
      - "2222:2222"
    environment:
      WONDERWALL_OPENID_CLIENT_ID: "fia-frontend"
      WONDERWALL_OPENID_CLIENT_JWK: >
        {
          "kty":"RSA",
          "alg":"RS256",
          "use":"sig",
          "p":"_xCPvqs85ZZVg460Qfot26rQoNRPTOVDo5p4nqH3ep6BK_5TvoU5LFXd26W-1V1Lc5fcvvftClPOT201xgat4DVtliNtoc8od_tWr190A3AzbsAVFOx0nKa5uhLBxP9SsPM84llp6PXF6QTMGFiPYuoLDaQQqL1K4BbHq3ZzF2M",
          "q":"7QLqW75zkfSDrn5rMoF50WXyB_ysNx6-2SvaXKGXaOn80IR7QW5vwkleJnsdz_1kr04rJws2p4HBJjUFfSJDi1Dapj7tbIwb0a1szDs6Y2fAa3DlzgXZCkoE2TIrW6UITgs14pI_a7RasclE71FpoZ78XNBvj3NmZugkNLBvRjs",
          "d":"f7aT4poed8uKdcSD95mvbfBdb6X-M86d99su0c390d6gWwYudeilDugH9PMwqUeUhY0tdaRVXr6rDDIKLSE-uEyaYKaramev0cG-J_QWYJU2Lx-4vDGNHAE7gC99o1Ee_LXqMDCBawMYyVcSWx7PxGQfzhSsARsAIbkarO1sg9zsqPS4exSMbK8wyCTPgRbnkB32_UdZSGbdSib1jSYyyoAItZ8oZHiltVsZIlA97kS4AGPtozde043NC7Ik0uEzgB5qJ_tR7vW8MfDrBj6da2NrLh0UH-q28dooBO1vEu0rvKZIescXYk9lk1ZakHhhpZaLykDOGzxCpronzP3_kQ",
          "e":"AQAB",
          "qi":"9kMIR6pEoiwN3M6O0n8bnh6c3KbLMoQQ1j8_Zyir7ZIlmRpWYl6HtK0VnD88zUuNKTrQa7-jfE5uAUa0PubzfRqybACb4S3HIAuSQP00_yCPzCSRrbpGRDFqq-8eWVwI9VdiN4oqkaaWcL1pd54IDcHIbfk-ZtNtZgsOlodeRMo",
          "dp":"VUecSAvI2JpjDRFxg326R2_dQWi6-uLMsq67FY7hx8WnOqZWKaUxcHllLENGguAmkgd8bv1F6-YJXNUO3Z7uE8DJWyGNTkSNK1CFsy0fBOdGywi-A7jrZFT6VBRhZRRY-YDaInPyzUkfWsGX26wAhPnrqCvqxgBEQJhdOh7obDE",
          "dq":"7EUfw92T8EhEjUrRKkQQYEK0iGnGdBxePLiOshEUky3PLT8kcBHbr17cUJgjHBiKqofOVNnE3i9nkOMCWcAyfUtY7KmGndL-WIP-FYplpnrjQzgEnuENgEhRlQOCXZWjNcnPKdKJDqF4WAtAgSIznz6SbSQMUoDD8IoyraPFCck",
          "n":"7CU8tTANiN6W_fD9SP1dK2vQvCkf7-nwvBYe5CfANV0_Bb0ZmQb77FVVsl1beJ7EYLz3cJmL8Is1RCHKUK_4ydqihNjEWTyZiQoj1i67pkqk_zRvfQa9raZR4uZbuBxx7dWUoPC6fFH2F_psAlHW0zf90fsLvhB6Aqq3uvO7XXqo8qNl9d_JSG0Rg_2QUYVb0WKmPVbbhgwtkFu0Tyuev-VZ9IzTbbr5wmZwEUVY7YAi73pDJkcZt5r2WjOF_cuIXe-O2vwbOrRgmJfHO9--mVLdATnEyrb6q2oy_75h6JjP-R4-TD1hyoFFoE2gmj-kSS6Z_Gggljs3Aw7--Nh10Q"
        }
      WONDERWALL_OPENID_WELL_KNOWN_URL: http://host.docker.internal:6969/azure/.well-known/openid-configuration
      WONDERWALL_INGRESS: http://localhost:2222
      WONDERWALL_BIND_ADDRESS: 0.0.0.0:2222
      WONDERWALL_UPSTREAM_HOST: host.docker.internal:5173
      WONDERWALL_AUTO_LOGIN: true
    restart: unless-stopped
    command: >
      --log-level=debug

  wiremock:
    container_name: wiremock
    image: wiremock/wiremock
    ports:
      - "9090:8080"
    volumes:
      - ./wiremock-stubs:/home/wiremock
    restart: unless-stopped
    command:
      - -global-response-templating

  fia-database:
    container_name: fia-database
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: test
    ports:
      - 5432:5432
    volumes:
      - fia-database-data:/var/lib/postgresql/data
    restart: unless-stopped

  kafka:
    container_name: kafka
    image: confluentinc/cp-kafka:7.4.0
    ports:
      - 9092:9092
      - 9093:9093
      - 9094:9094
    environment:
      CLUSTER_ID: 4L6g3nShT-eMCtK--X86sw
      KAFKA_NODE_ID: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: BROKER:PLAINTEXT,PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_LISTENERS: BROKER://0.0.0.0:9092,PLAINTEXT://0.0.0.0:9093,CONTROLLER://0.0.0.0:9094
      KAFKA_ADVERTISED_LISTENERS: BROKER://kafka:9092,PLAINTEXT://kafka:9093
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9094
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_OFFSETS_TOPIC_NUM_PARTITIONS: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      TZ: Europe/Oslo
    volumes:
      - ./scripts/setup_kraft.sh:/tmp/setup_kraft.sh
    restart: unless-stopped
    command: "bash -c '/tmp/setup_kraft.sh && /etc/confluent/docker/run'"

  fia-backend:
    container_name: fia-backend
    build:
      context: lydia-api

    depends_on:
      - fia-database
      - kafka
      - authserver
      - wiremock
    ports:
      - 8080:8080
    environment:
      # Postgres env
      NAIS_DATABASE_LYDIA_API_LYDIA_API_DB_HOST: fia-database
      NAIS_DATABASE_LYDIA_API_LYDIA_API_DB_PORT: 5432
      NAIS_DATABASE_LYDIA_API_LYDIA_API_DB_USERNAME: postgres
      NAIS_DATABASE_LYDIA_API_LYDIA_API_DB_PASSWORD: test
      NAIS_DATABASE_LYDIA_API_LYDIA_API_DB_DATABASE: postgres
      # Authserver env
      AZURE_APP_CLIENT_ID: lydia-api
      AZURE_OPENID_CONFIG_TOKEN_ENDPOINT: http://host.docker.internal:6969/azure/token
      AZURE_APP_JWK: >
        {
            "p": "5E2G6sOsbC6oBwx-EiRotMLYfVqOmzvRKxe2_hiquWQxg8bhVTf2XkqLPsHZB3Zy36pQlBghljW7Eti72tkA6oDwaTBkHaL_FVs2xzHHKPfh2j1XQxhr8VriPKNVGIr3ueRRGlIMKd3shwcpkB9fHrcN9BIl-Ml2VT5cZmtYGL8",
            "kty": "RSA",
            "q": "yYdq__td3d5COnjmYOzZiw-Nqr83m2SfF5nToey-HM3Za2BSqQLBC2Xy7Sefo7FA-9GzG76Wd3Yp6ofP6Dzp93-kjtcVBBoppJSYKzvC11L0rdsV3kVd7iRxP1MLqSO2DY6CHRpOk2YxqgskGt3-IKwZ9p3sYGEMH8iAuT1V0Wc",
            "d": "boLVdxUVZNCOiGQqaNMxYROupjqkwBbCD2JujIVLgRvgPRSqFLeWkttAVn6ekXT3vxss8VNwQkMXuDhfuy2MQjlfXPFfDM4go5Ec7ZMxmhzXsP-tnS-jaVC0MWsNsZyBVJuxmlxsqY5vt8A8vrYhatO82w6D_tWqkPdQkupyL6-U_u8ikxMMo0SmD3OYAzVhgvrnfinh7itGrmgo9xqEt5IjFJ9f1BFy21o5YA0LReNeaOrMYhZoUIQAjcTpFgEsU5vORT8boXIN3_Bbby32_xlizXBtXlWxWRMN0k3EuzSPar8QvAXdBZf8GsARoSrbfqBtDKQyp94tl5bCH5XIiQ",
            "e": "AQAB",
            "use": "sig",
            "kid": "azure",
            "qi": "Hu7hgJvc5XvFf6OZeHbYkKEgwttO-INjMVSWvBCR89KKN2Njy8e7zAu7T25YuVxbxtLAvwg-sA-ZtELH28DQhR7AnNmJkh_r0IWuOUHROMrCO2iix9Jl1xrCPanQLGx9iTS7LltaYO5jrv9GGYmFBqIvGByKxI7FytgeXhh2NLk",
            "dp": "odtw_nnRgTUmvTCXJMeZUCYfk-ei2N10ssdyXf0g9KTbEeDrGh691SWmSMzn0Ami8X1u-T-OeE8JnRf5PvPAWYEmcHz1TamkjQCI-noJB7uN7Mq2VgQ3avqTEIh_qRHFBY6gDTgEFZ6XtTdXuSz0o_MFuncvYo16Dn9SxO3vnEM",
            "dq": "GugXoyG-gJbiJMhridlVmjlzYq6xD_A5RX9mQCJJp7LcKnfr0WDqwUjVTFCUAdjyoix3S2cA0-ZU5llHquwnGMJUCDYzOh78HFsyjeMmunT68hNkMg704YzACgJedjCsZ9b1DEms4AUu8FMYePXWrioMNV8UZjHO2pd8iD7mLFU",
            "n": "s7mjPNyx4wtQ-ij0VIAvfooN9m2qgqidE7wJ50zAzmG2cS9Y9XpV09KJAAgP21RVQNqbxU3BCwltYD5bhsYSn-T5HZ7uXbjb9zgSY5XUM0TWGMV7qqdISWmHCH6-LYZGrJiN7ofDW3XGINsRlxj3gZbSuSNnXdbreOC97wT5i-qVxWt9xhobB60Jjf3gNiA3XMaOGyE47Ty-6WMH_zs_sENWXQ0eGoD58DROqbF1CUb_9ppubK9nU4Sjo0ih57J14n8aKZVEWg4uN02Gv0TL1ratvyDTwRZrtKprfgFBzylxtV2zkvhETsi7zkrzjsrv4v8hap6V32NgXc8E1xDj2Q"
        }
      AZURE_OPENID_CONFIG_ISSUER: http://host.docker.internal:6969/azure
      AZURE_OPENID_CONFIG_JWKS_URI: http://host.docker.internal:6969/azure/jwks
      AZURE_GRAPH_URL: http://host.docker.internal:9090/v1.0
      FIA_SUPERBRUKER_GROUP_ID: ensuperbrukerGroupId
      FIA_SAKSBEHANDLER_GROUP_ID: ensaksbehandlerGroupId
      FIA_LESETILGANG_GROUP_ID: enlesetilgangGroupId
      TEAM_PIA_GROUP_ID: enTeamPiaGroupId
      # Kafka env
      KAFKA_BROKERS: "BROKER://kafka:9092,PLAINTEXT://kafka:9092"
      KAFKA_TRUSTSTORE_PATH: ""
      KAFKA_KEYSTORE_PATH: ""
      KAFKA_CREDSTORE_PASSWORD: ""
      # Backend spesifikk env
      BRREG_UNDERENHET_URL: /brregmock/enhetsregisteret/api/underenheter/lastned
      CONSUMER_LOOP_DELAY: 1
      SSB_NARINGS_URL: /naringmock/api/klass/v1/30/json
      NAIS_CLUSTER_NAME: "lokal"
      # Spesifikk for remote debugging
      SALESFORCE_TOKEN_HOST: http://host.docker.internal:9090
      SALESFORCE_CLIENT_ID: clientId
      SALESFORCE_CLIENT_SECRET: clientSecret
      SALESFORCE_USERNAME: username
      SALESFORCE_PASSWORD: password
      SALESFORCE_SECURITY_TOKEN: securityToken
    restart: unless-stopped

  redis:
    container_name: redis
    image: redis:7-alpine
    ports:
      - 6379:6379
    command: ["redis-server", "--user brukernavn on +@all ~* >passord"]
    restart: unless-stopped

  fia-frontend:
    container_name: fia-frontend
    build:
      context: lydia-radgiver-frontend/server
      dockerfile: Dockerfile.dev
    depends_on:
      - fia-backend
      - redis
      - wonderwall
    ports:
      - 3000:3000
    environment:
      REDIS_URI_FIASESSIONS: redis://redis:6379
      REDIS_USERNAME_FIASESSIONS: brukernavn
      REDIS_PASSWORD_FIASESSIONS: passord
      NAIS_CLUSTER_NAME: dev
      SESSION_SECRET: secret
      CSRF_SECRET: csrf
      COOKIE_SECRET: cookie
      OBO_TOKEN_ENC_KEY: bogus
      NAIS_NAMESPACE: pia
      LYDIA_API_URI: http://fia-backend:8080
      SERVER_PORT: 3000
      AZURE_OPENID_CONFIG_JWKS_URI: http://host.docker.internal:6969/azure/jwks
      AZURE_APP_CLIENT_ID: fia-frontend
      AZURE_APP_CLIENT_SECRET: secret
      AZURE_OPENID_CONFIG_ISSUER: http://host.docker.internal:6969/azure
      AZURE_OPENID_CONFIG_TOKEN_ENDPOINT: http://host.docker.internal:6969/azure/token
      FIA_SUPERBRUKER_GROUP_ID: ensuperbrukerGroupId
      FIA_SAKSBEHANDLER_GROUP_ID: ensaksbehandlerGroupId
      FIA_LESETILGANG_GROUP_ID: enlesetilgangGroupId
    restart: unless-stopped

  fia-arbeidsgiver:
    container_name: fia-arbeidsgiver
    build:
      context: fia-arbeidsgiver
    depends_on:
      - redis
      - authserver
    ports:
      - 8081:8080
    environment:
      NAIS_CLUSTER_NAME: dev-gcp
      TOKEN_X_ISSUER: http://host.docker.internal:6969/idporten
      TOKEN_X_JWKS_URI: http://host.docker.internal:6969/idporten/jwks
      TOKEN_X_CLIENT_ID: fia-arbeidsgiver
      TOKEN_X_PRIVATE_JWK: >
        {
            "p": "5E2G6sOsbC6oBwx-EiRotMLYfVqOmzvRKxe2_hiquWQxg8bhVTf2XkqLPsHZB3Zy36pQlBghljW7Eti72tkA6oDwaTBkHaL_FVs2xzHHKPfh2j1XQxhr8VriPKNVGIr3ueRRGlIMKd3shwcpkB9fHrcN9BIl-Ml2VT5cZmtYGL8",
            "kty": "RSA",
            "q": "yYdq__td3d5COnjmYOzZiw-Nqr83m2SfF5nToey-HM3Za2BSqQLBC2Xy7Sefo7FA-9GzG76Wd3Yp6ofP6Dzp93-kjtcVBBoppJSYKzvC11L0rdsV3kVd7iRxP1MLqSO2DY6CHRpOk2YxqgskGt3-IKwZ9p3sYGEMH8iAuT1V0Wc",
            "d": "boLVdxUVZNCOiGQqaNMxYROupjqkwBbCD2JujIVLgRvgPRSqFLeWkttAVn6ekXT3vxss8VNwQkMXuDhfuy2MQjlfXPFfDM4go5Ec7ZMxmhzXsP-tnS-jaVC0MWsNsZyBVJuxmlxsqY5vt8A8vrYhatO82w6D_tWqkPdQkupyL6-U_u8ikxMMo0SmD3OYAzVhgvrnfinh7itGrmgo9xqEt5IjFJ9f1BFy21o5YA0LReNeaOrMYhZoUIQAjcTpFgEsU5vORT8boXIN3_Bbby32_xlizXBtXlWxWRMN0k3EuzSPar8QvAXdBZf8GsARoSrbfqBtDKQyp94tl5bCH5XIiQ",
            "e": "AQAB",
            "use": "sig",
            "kid": "idporten",
            "qi": "Hu7hgJvc5XvFf6OZeHbYkKEgwttO-INjMVSWvBCR89KKN2Njy8e7zAu7T25YuVxbxtLAvwg-sA-ZtELH28DQhR7AnNmJkh_r0IWuOUHROMrCO2iix9Jl1xrCPanQLGx9iTS7LltaYO5jrv9GGYmFBqIvGByKxI7FytgeXhh2NLk",
            "dp": "odtw_nnRgTUmvTCXJMeZUCYfk-ei2N10ssdyXf0g9KTbEeDrGh691SWmSMzn0Ami8X1u-T-OeE8JnRf5PvPAWYEmcHz1TamkjQCI-noJB7uN7Mq2VgQ3avqTEIh_qRHFBY6gDTgEFZ6XtTdXuSz0o_MFuncvYo16Dn9SxO3vnEM",
            "dq": "GugXoyG-gJbiJMhridlVmjlzYq6xD_A5RX9mQCJJp7LcKnfr0WDqwUjVTFCUAdjyoix3S2cA0-ZU5llHquwnGMJUCDYzOh78HFsyjeMmunT68hNkMg704YzACgJedjCsZ9b1DEms4AUu8FMYePXWrioMNV8UZjHO2pd8iD7mLFU",
            "n": "s7mjPNyx4wtQ-ij0VIAvfooN9m2qgqidE7wJ50zAzmG2cS9Y9XpV09KJAAgP21RVQNqbxU3BCwltYD5bhsYSn-T5HZ7uXbjb9zgSY5XUM0TWGMV7qqdISWmHCH6-LYZGrJiN7ofDW3XGINsRlxj3gZbSuSNnXdbreOC97wT5i-qVxWt9xhobB60Jjf3gNiA3XMaOGyE47Ty-6WMH_zs_sENWXQ0eGoD58DROqbF1CUb_9ppubK9nU4Sjo0ih57J14n8aKZVEWg4uN02Gv0TL1ratvyDTwRZrtKprfgFBzylxtV2zkvhETsi7zkrzjsrv4v8hap6V32NgXc8E1xDj2Q"
        }
      TOKEN_X_TOKEN_ENDPOINT: http://host.docker.internal:6969/idporten/token
      ALTINN_RETTIGHETER_PROXY_URL: http://host.docker.internal:9090/altinn
      ALTINN_RETTIGHETER_PROXY_CLIENT_ID: local:arbeidsgiver:altinn-rettigheter-proxy
      KAFKA_BROKERS: "BROKER://kafka:9092,PLAINTEXT://kafka:9092"
      KAFKA_TRUSTSTORE_PATH: ""
      KAFKA_KEYSTORE_PATH: ""
      KAFKA_CREDSTORE_PASSWORD: ""
      REDIS_URI_FIA_SAMARBEIDSSTATUS: redis://redis:6379
      REDIS_USERNAME_FIA_SAMARBEIDSSTATUS: brukernavn
      REDIS_PASSWORD_FIA_SAMARBEIDSSTATUS: passord

  fia-arbeidsgiver-frontend:
    container_name: fia-arbeidsgiver-frontend
    build:
      context: fia-arbeidsgiver-frontend
    depends_on:
      - fia-arbeidsgiver
    ports:
      - 3001:3000
    environment:
      FIA_ARBEIDSGIVER_HOSTNAME: host.docker.internal:8081


volumes:
  fia-database-data:
